package Strings;
/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/
public class FindDifference {

    public static void main(String[] args) {
        //System.out.println(findTheDifferenc("abcd","abcde"));
        System.out.println(bruteFindTheDifference("abcd","abcde"));
    }

    //Brute Force Approach
    public static char bruteFindTheDifference(String s,String t){
        int[] count = new int[26];
        for(char ch : t.toCharArray()){
            count[ch-'a']++;
        }

        for(char ch : s.toCharArray()){
            count[ch-'a']--;
        }

        for(int i=0;i<count.length;i++){
            if(count[i]!=0)
                return (char) (i+'a');
        }
        return '0';
    }

    //Optimized Approch
    public static char findTheDifferenc(String s,String t){
        int sum1=0,sum2=0;
        for(char ch :s.toCharArray()){
            sum1 += ch;
        }
        for(char ch : t.toCharArray()){
            sum2 += ch;
        }
        return (char) (sum2-sum1);
    }
}
